server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ong_manager_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    username: andreibanciu53@gmail.com
    password: tzmqtynqskhmnxsx
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 587
          auth: true
          starttls:
            enable: true
            required: true
  security:
    oauth2:
      client:
        default:
          client-id: client
          secret: secret
          scope: openid
          auth-method: client_secret_basic
          grant-type: authorization_code
          redirect-uri: http://localhost:4200/authorized
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8080/oauth2/jwks

logging:
  level:
    root: INFO
    com.example: DEBUG

admin:
  email: admin@mail.com

app:
  base-url: http://localhost:8080
  client-url: http://localhost:4200
  endpoints:
    account:
      registration:
        set-password: /auth/set-password/
  email:
    support: suport@ongmanager.ro

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: true
